name: Benchmarks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0' # Weekly Sunday 04:00 UTC

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install -r requirements-dev.txt
      - name: Configure AWS credentials (OIDC)
        if: env.AWS_ROLE_TO_ASSUME
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION || 'us-east-1' }}
      - name: Run benchmarks and publish metrics
        env:
          RS_HOST: ${{ secrets.RS_HOST }}
          RS_USER: ${{ secrets.RS_USER }}
          RS_PASSWORD: ${{ secrets.RS_PASSWORD }}
          RS_DB: ${{ secrets.RS_DB || 'dev' }}
          RS_PORT: ${{ secrets.RS_PORT || '5439' }}
          PROJECT: ${{ vars.PROJECT || 'bank-deposits-mart-final' }}
          BENCH_NAMESPACE: ${{ vars.BENCH_NAMESPACE || format('{0}/Benchmarks', vars.PROJECT) }}
        run: |
          python scripts/benchmarks.py

