name: Terraform Validate

on:
  pull_request:
    paths:
      - 'infra/terraform/**'
      - 'infra/bootstrap/**'
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform fmt (check)
        working-directory: infra/terraform
        run: terraform fmt -check -recursive

      - name: Terraform init (no backend)
        working-directory: infra/terraform
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: infra/terraform
        run: terraform validate

