name: Terraform Validate

on:
  pull_request:
    paths:
      - 'infra/terraform/**'
      - '.tflint.hcl'
  push:
    branches: [ main ]
    paths:
      - 'infra/terraform/**'
      - '.tflint.hcl'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - name: Terraform fmt
        run: terraform -chdir=infra/terraform fmt -check -recursive
      - name: Terraform init (no backend)
        run: terraform -chdir=infra/terraform init -backend=false
      - name: Terraform validate
        run: terraform -chdir=infra/terraform validate -no-color
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
      - name: TFLint init
        run: tflint --init
      - name: TFLint run
        run: tflint -c .tflint.hcl infra/terraform
      - name: Checkov (IaC security)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/terraform
          framework: terraform

